Repository openshift/ci-search, pull requests merged in 2019-04, with the labels that each got.

#8 Add better logging when search results fail
  cmd/search/http.go
Labels: approved, lgtm, size/XS

#9 cmd/search/http: Pull query parsing out into parseRequest
  cmd/search/http.go
Labels: approved, lgtm, size/M

#11 cmd/search/grep: Change '--color never' -> '--color=never'
  cmd/search/grep.go
Labels: approved, lgtm, size/XS

#10 testgrid/cmd/build-indexer: Closing paren for -gcp-service-account help
  testgrid/cmd/build-indexer/main.go
Labels: approved, lgtm, size/XS

#13 Index deck periodically if URL is set
  cmd/search/http.go
  cmd/search/main.go
Labels: approved, lgtm, size/L

#15 Disable autocomplete
  cmd/search/http.go
Labels: approved, lgtm, size/XS

#20 cmd/search/grep: Preserve 'initial' arguments for pre-index SearchPaths
  cmd/search/grep.go
Labels: approved, lgtm, size/XS
